source "https://rubygems.org"

gem "fastlane"
gem "xcpretty"
gem "xcpretty-junit-formatter"
gem "xcpretty-travis-formatter"
gem "dotenv", "~> 2.8"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)