name: DotDash

options:
  bundleIdPrefix: br.com.bitxlabs.app.dotdash.ios
  xcodeVersion: "26.0.1"
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    iOS: "17.2"
  categories:
    - utilities
    - Entertainment
  organizationName: BitX Labs
  organizationIdentifier: br.com.bitxlabs

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: "12.3.0"

settings:
  GENERATE_INFOPLIST_FILE: NO
  base:
    DEVELOPMENT_TEAM: Z6MUH3V2QB
    SWIFT_VERSION: 5.10
    SWIFT_APPROACHABLE_CONCURRENCY: YES
    SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY: YES
    ENABLE_BITCODE: NO
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: YES_AGGRESSIVE
    CLANG_CXX_LANGUAGE_STANDARD: gnu++20
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
    CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
    ENABLE_STRICT_OBJC_MSGSEND: YES
    GCC_C_LANGUAGE_STANDARD: gnu17
    GCC_NO_COMMON_BLOCKS: YES
    GCC_WARN_64_TO_32_BIT_CONVERSION: YES
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: YES
    GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
    GCC_WARN_UNUSED_FUNCTION: YES
    GCC_WARN_UNUSED_VARIABLE: YES
    LOCALIZATION_PREFERS_STRING_CATALOGS: YES
    MTL_FAST_MATH: YES
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
  configurations:
    Debug:
      buildSettings:
        ENABLE_TESTABILITY: YES
        GCC_PREPROCESSOR_DEFINITIONS:
          - DEBUG=1
          - $(inherited)
        MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG $(inherited)
        SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      buildSettings:
        ENABLE_NS_ASSERTIONS: NO
        MTL_ENABLE_DEBUG_INFO: NO
        SWIFT_COMPILATION_MODE: wholemodule
        SWIFT_OPTIMIZATION_LEVEL: -O

targets:
  DotDash:
    info:
      path: DotDash/SupportingFiles/Info.plist
      properties:
        CFBundleIdentifier: br.com.bitxlabs.app.dotdash.ios
        CFBundleName: DotDash
        CFBundleDisplayName: DotDash
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSApplicationCategoryType: public.app-category.utilities
        NSCameraUsageDescription: This app requires camera access to capture morse code signals.
        NSNotificationUsageDescription: This app requires notification access to send you alerts and updates.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    type: application
    platform: iOS
    sources: DotDash
    dependencies:
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseAnalytics
    resources:
      - DotDash/Resources/Assets.xcassets
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: br.com.bitxlabs.app.dotdash.ios
      ENABLE_PREVIEWS: YES
      SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
      MARkETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
    postBuildScripts:
      - path: Scripts/crashlytics.sh
        name: "[Run] Crashlytics"
        inputFiles:
          - "$(SRCROOT)/$(TARGET_NAME)/SupportingFiles/GoogleService-Info.plist"
        shell: /bin/sh
        basedOnDependencyAnalysis: false
      - path: Scripts/lint.sh
        name: "[Run] SwiftLint"
        basedOnDependencyAnalysis: false
      - path: Scripts/format.sh
        name: "[Run] Swiftformat"
        basedOnDependencyAnalysis: false

  DotDashTests:
    type: bundle.unit-test
    platform: iOS
    sources: DotDashTests
    dependencies:
      - target: DotDash
    postBuildScripts:
      - path: Scripts/lint.sh
        name: "[Run] SwiftLint"
        basedOnDependencyAnalysis: false
      - path: Scripts/format.sh
        name: "[Run] Swiftformat"
        basedOnDependencyAnalysis: false

  DotDashUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: DotDashUITests
    dependencies:
      - target: DotDash
    postBuildScripts:
      - path: Scripts/lint.sh
        name: "[Run] SwiftLint"
        basedOnDependencyAnalysis: false
      - path: Scripts/format.sh
        name: "[Run] Swiftformat"
        basedOnDependencyAnalysis: false
