name: DotDash

# Options
options:
  deploymentTarget: 
    iOS: 15.0
    watchOS: 8.0
  indentWidth: 2
  tabWidth: 2

# Settings
settings:
  GENERATE_INFOPLIST_FILE: NO
  SWIFT_VERSION: "6.0"

# Config
configFiles:
  Debug: App/DotDash/Sources/Configs/debug.xcconfig
  Release: App/DotDash/Sources/Configs/release.xcconfig

# Packages
packages:
  Core: 
    path: ./Core
  Components:
    path: ./Components
  DotDashIOS:
    path: ./iOS
  DotDashWatchOS:
    path: ./watchOS
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: "12.3.0"

# Reusable templates
targetTemplates:
  LintAndFormat:
    postBuildScripts:
      - path: Scripts/lint.sh
        name: "[Run] SwiftLint"
        basedOnDependencyAnalysis: false
      - path: Scripts/format.sh
        name: "[Run] Swiftformat"
        basedOnDependencyAnalysis: false
  Crashlytics:
    postBuildScripts:
      - path: Scripts/crashlytics.sh
        name: "[Run] Crashlytics"
        inputFiles:
          - "$(SRCROOT)/$(TARGET_NAME)/SupportingFiles/GoogleService-Info.plist"
        shell: /bin/sh
        basedOnDependencyAnalysis: false

# Targets
targets:
  DotDash:
    type: application
    platform: iOS
    sources:
      - path: App/DotDash
        createIntermediateGroups: true
        exclude:
          - App/DotDash/Sources/SupportingFiles/GoogleService-Info-release.plist
    resources:
      - App/DotDash/Resources
      - App/DotDash/Sources/SupportingFiles/GoogleService-Info.plist
    configFiles:
      Debug: App/DotDash/Sources/Configs/dotdash-debug.xcconfig
      Release: App/DotDash/Sources/Configs/dotdash-release.xcconfig
    info:
      path: App/DotDash/Sources/SupportingFiles/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDisplayName: $(PRODUCT_NAME)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSApplicationCategoryType: public.app-category.utilities
        NSCameraUsageDescription: This app requires camera access to capture morse code signals.
        NSNotificationUsageDescription: This app requires notification access to send you alerts and updates.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    attributes:
      DevelopmentTeam: $(DEVELOPMENT_TEAM)
      ProvisioningStyle: Automatic
    settings:
      INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
      INFOPLIST_KEY_CFBundleDisplayName: $(PRODUCT_NAME)
    dependencies:
      - package: Core
      - package: Components
      - package: DotDashIOS
      - package: DotDashWatchOS
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseAnalytics
    templates:
      - Crashlytics
      - LintAndFormat

# Unit Tests
  DotDashTests:
    type: bundle.unit-test
    platform: iOS
    configFiles:
      Debug: App/Tests/DotDashTests/Config/DotDashTests.xcconfig
      Release: App/Tests/DotDashTests/Config/DotDashTests.xcconfig
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_FILE: ""
    sources: App/Tests/DotDashTests
    dependencies:
      - target: DotDash
    templates:
      - LintAndFormat

# UI Tests
  DotDashUITests:
    type: bundle.ui-testing
    platform: iOS
    configFiles:
      Debug: App/Tests/DotDashUITests/Config/DotDashUITests.xcconfig
      Release: App/Tests/DotDashUITests/Config/DotDashUITests.xcconfig
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_FILE: ""
    sources: App/Tests/DotDashUITests
    dependencies:
      - target: DotDash
    templates:
      - LintAndFormat

schemes:
  DotDash:
    build:
      targets:
        DotDash: all
    run:
      configuration: Debug
    test:
      testPlans:
        - path: App/Tests/DotDash.xctestplan
          defaultPlan: true
    archive:
      configuration: Release
    analyze:
      configuration: Debug
    profile:
      configuration: Release